return {
  {
    "f4z3r/gruvbox-material.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require("gruvbox-material").setup({
        terminal_colors = true,
        undercurl = true,
        underline = true,
        bold = true,
        italic = {
          strings = false,
          emphasis = true,
          comments = true,
          operators = false,
          folds = true,
        },
        strikethrough = true,
        invert_selection = false,
        invert_signs = false,
        invert_tabline = false,
        invert_intend_guides = false,
        inverse = true,
        contrast = "hard",
        palette_overrides = {
          dark0_hard = "#1a1a1a",
          dark0 = "#1a1a1a",
          dark0_soft = "#252525",
          dark1 = "#252525",
          dark2 = "#4d4d4d",
          dark3 = "#4d4d4d",
          dark4 = "#808080",
          light0_hard = "#d9d9d9",
          light0 = "#d9d9d9",
          light0_soft = "#d9d9d9",
          light1 = "#d9d9d9",
          light2 = "#b3b3b3",
          light3 = "#b3b3b3",
          light4 = "#808080",
          gray = "#808080",
        },
        overrides = {
          Normal = { bg = "#1a1a1a" },
          NormalFloat = { bg = "#1a1a1a" },
          FloatBorder = { fg = "#4d4d4d", bg = "#1a1a1a" },
          SignColumn = { bg = "#1a1a1a" },
          CursorLine = { bg = "#252525" },
          CursorLineNr = { fg = "#b3b3b3", bg = "#252525" },
          LineNr = { fg = "#808080" },
          VertSplit = { fg = "#4d4d4d" },
          WinSeparator = { fg = "#4d4d4d" },
          StatusLine = { bg = "#1a1a1a", fg = "#d9d9d9" },
          StatusLineNC = { bg = "#1a1a1a", fg = "#808080" },
          Pmenu = { bg = "#252525", fg = "#d9d9d9" },
          PmenuSel = { bg = "#4d4d4d", fg = "#d9d9d9" },
          PmenuSbar = { bg = "#252525" },
          PmenuThumb = { bg = "#4d4d4d" },
          TabLine = { bg = "#1a1a1a", fg = "#808080" },
          TabLineFill = { bg = "#1a1a1a" },
          TabLineSel = { bg = "#252525", fg = "#d9d9d9" },
          DiagnosticError = { fg = "#fb4934" },
          DiagnosticWarn = { fg = "#fabd2f" },
          DiagnosticInfo = { fg = "#83a598" },
          DiagnosticHint = { fg = "#8ec07c" },
          GitSignsAdd = { fg = "#b8bb26" },
          GitSignsChange = { fg = "#83a598" },
          GitSignsDelete = { fg = "#fb4934" },
          NvimTreeNormal = { bg = "#1a1a1a" },
          NvimTreeNormalNC = { bg = "#1a1a1a" },
          NvimTreeWinSeparator = { fg = "#4d4d4d", bg = "#1a1a1a" },
          TelescopeNormal = { bg = "#1a1a1a" },
          TelescopeBorder = { fg = "#4d4d4d", bg = "#1a1a1a" },
          TelescopePromptBorder = { fg = "#4d4d4d", bg = "#1a1a1a" },
          TelescopeResultsBorder = { fg = "#4d4d4d", bg = "#1a1a1a" },
          TelescopePreviewBorder = { fg = "#4d4d4d", bg = "#1a1a1a" },
          WhichKeyFloat = { bg = "#1a1a1a" },
          WhichKeyBorder = { fg = "#4d4d4d" },
        },
        dim_inactive = false,
        transparent_mode = false,
      })
    end,
  },
}
